### ISSUE TITLE
VSX support

### ISSUE THREAD

**Issue by Alcap** [CheckPointSW/CheckPointAnsibleGAIACollection#1]
Hi,
I'd like to know if this module is supported for VSX clusters. I'm not entirely sure that the Gaia API is available for VSX, did a quick google search and found nothing.
Do you know if this is supported on VSX clusters? Is there another way to quickly gather information on the interfaces of a VSX cluster or, ideally, per VS?

Thanks!

**Comment by chkp-yuvalfe** [comment]
Hi @Alcap, sorry for the delayed answer. Unfortunately, Gaia API is available for each member of VSX (each Gaia machine), but it isn't supported for VSX cluser or per VS.
