### ISSUE TITLE
Any plans to extend this?

### ISSUE THREAD

**Issue by hvdkooij** [CheckPointSW/CheckPointAnsibleGAIACollection#4]
Hi,

Ar there any plans to extend this?
It seems only a limited set of the GAIA REST API command is included.

Are you willing to accept contributions from others to extend it?

**Comment by chkp-yuvalfe** [comment]
Hi @hvdkooij, 

This is an initial version of GAIA ansible collection. 
We are working on extending it in the future. 
Thanks for the interest in our collection, but currently we are not accepting contributions from others.

Thanks :)
Yuval
